
[[task]]
name="baidu"
location="us"
historyfiveDayUrl="https://finance.pae.baidu.com/selfselect/getstockquotation?code=BIDU&all=1&ktype=1&isIndex=false&isBk=false&isBlock=false&isFutures=false&stockType=us&group=quotation_fiveday_us&finClientType=pc"
url="https://finance.pae.baidu.com/vapi/stockshort?code=BIDU&market=us&finClientType=pc"
prometheusWrite="http://localhost:8428/write"
prometheusExport= "http://localhost:8428/api/v1/import/prometheus"
[[task]]
name="baidu"
location="hk"
historyfiveDayUrl="https://finance.pae.baidu.com/selfselect/getstockquotation?code=09888&all=1&ktype=1&isIndex=false&isBk=false&isBlock=false&isFutures=false&stockType=hk&group=quotation_fiveday_hk&finClientType=pc"
url="http://finance.pae.baidu.com/vapi/stockshort?code=09888&market=hk&finClientType=pc"
prometheusWrite="http://localhost:8428/write"
prometheusExport= "http://localhost:8428/api/v1/import/prometheus"


